/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
package com.cfs.sqlkv.compile.parse;

public interface SQLParserConstants {

    int EOF = 0;
    int ADD = 5;
    int ALL = 6;
    int ALLOCATE = 7;
    int ALTER = 8;
    int AND = 9;
    int ANY = 10;
    int ARE = 11;
    int AS = 12;
    int ASC = 13;
    int ASSERTION = 14;
    int AT = 15;
    int AUTHORIZATION = 16;
    int AVG = 17;
    int BEGIN = 18;
    int BETWEEN = 19;
    int BINARY = 20;
    int BIT = 21;
    int BOTH = 22;
    int BY = 23;
    int CASCADE = 24;
    int CASCADED = 25;
    int CASE = 26;
    int CAST = 27;
    int CHAR = 28;
    int CHARACTER = 29;
    int CHARACTER_LENGTH = 30;
    int CHECK = 31;
    int CLOSE = 32;
    int COALESCE = 33;
    int COLLATE = 34;
    int COLLATION = 35;
    int COLUMN = 36;
    int COMMIT = 37;
    int CONNECT = 38;
    int CONNECTION = 39;
    int CONSTRAINT = 40;
    int CONSTRAINTS = 41;
    int CONTINUE = 42;
    int CONVERT = 43;
    int CORRESPONDING = 44;
    int COUNT = 45;
    int CREATE = 46;
    int CROSS = 47;
    int CURRENT = 48;
    int CURRENT_DATE = 49;
    int CURRENT_TIME = 50;
    int CURRENT_TIMESTAMP = 51;
    int CURRENT_USER = 52;
    int CURSOR = 53;
    int D = 54;
    int DEALLOCATE = 55;
    int DEC = 56;
    int DECIMAL = 57;
    int DECLARE = 58;
    int _DEFAULT = 59;
    int DEFERRABLE = 60;
    int DEFERRED = 61;
    int DELETE = 62;
    int DESC = 63;
    int DESCRIBE = 64;
    int DIAGNOSTICS = 65;
    int DISCONNECT = 66;
    int DISTINCT = 67;
    int DOUBLE = 68;
    int DROP = 69;
    int ELSE = 70;
    int END = 71;
    int ENDEXEC = 72;
    int ESCAPE = 73;
    int EXCEPT = 74;
    int EXCEPTION = 75;
    int EXEC = 76;
    int EXECUTE = 77;
    int EXISTS = 78;
    int EXTERNAL = 79;
    int FALSE = 80;
    int FETCH = 81;
    int FIRST = 82;
    int FLOAT = 83;
    int FOR = 84;
    int FOREIGN = 85;
    int FOUND = 86;
    int FROM = 87;
    int FULL = 88;
    int FUNCTION = 89;
    int GET = 90;
    int GLOBAL = 91;
    int GO = 92;
    int GOTO = 93;
    int GRANT = 94;
    int GROUP = 95;
    int HAVING = 96;
    int HOUR = 97;
    int IDENTITY = 98;
    int IMMEDIATE = 99;
    int IN = 100;
    int INDICATOR = 101;
    int INITIALLY = 102;
    int INNER = 103;
    int INPUT = 104;
    int INSENSITIVE = 105;
    int INSERT = 106;
    int INT = 107;
    int INTEGER = 108;
    int INTERSECT = 109;
    int INTO = 110;
    int IS = 111;
    int ISOLATION = 112;
    int JOIN = 113;
    int KEY = 114;
    int LAST = 115;
    int LEADING = 116;
    int LEFT = 117;
    int LIKE = 118;
    int LOWER = 119;
    int MATCH = 120;
    int MAX = 121;
    int MIN = 122;
    int MINUTE = 123;
    int MODULE = 124;
    int NATIONAL = 125;
    int NATURAL = 126;
    int NCHAR = 127;
    int NEXT = 128;
    int NO = 129;
    int NOT = 130;
    int NULL = 131;
    int NULLIF = 132;
    int NUMERIC = 133;
    int OF = 134;
    int ON = 135;
    int ONLY = 136;
    int OPEN = 137;
    int OPTION = 138;
    int OR = 139;
    int ORDER = 140;
    int OUTER = 141;
    int OUTPUT = 142;
    int OVERLAPS = 143;
    int PAD = 144;
    int PARTIAL = 145;
    int PREPARE = 146;
    int PRESERVE = 147;
    int PRIMARY = 148;
    int PRIOR = 149;
    int PRIVILEGES = 150;
    int PROCEDURE = 151;
    int PUBLIC = 152;
    int READ = 153;
    int REAL = 154;
    int REFERENCES = 155;
    int RELATIVE = 156;
    int RESTRICT = 157;
    int REVOKE = 158;
    int RIGHT = 159;
    int ROLLBACK = 160;
    int ROWS = 161;
    int SCHEMA = 162;
    int SCROLL = 163;
    int SECOND = 164;
    int SELECT = 165;
    int SESSION_USER = 166;
    int SET = 167;
    int SMALLINT = 168;
    int SOME = 169;
    int SPACE = 170;
    int SQL = 171;
    int SQLCODE = 172;
    int SQLERROR = 173;
    int SQLSTATE = 174;
    int SUBSTRING = 175;
    int SUM = 176;
    int SYSTEM_USER = 177;
    int T = 178;
    int TABLE = 179;
    int TEMPORARY = 180;
    int TIMEZONE_HOUR = 181;
    int TIMEZONE_MINUTE = 182;
    int TO = 183;
    int TRANSACTION = 184;
    int TRANSLATE = 185;
    int TRANSLATION = 186;
    int TRAILING = 187;
    int TRIM = 188;
    int TRUE = 189;
    int TS = 190;
    int UNION = 191;
    int UNIQUE = 192;
    int UNKNOWN = 193;
    int UPDATE = 194;
    int UPPER = 195;
    int USER = 196;
    int USING = 197;
    int VALUE = 198;
    int VALUES = 199;
    int VARBINARY = 200;
    int VARCHAR = 201;
    int VARYING = 202;
    int VIEW = 203;
    int WHENEVER = 204;
    int WHERE = 205;
    int WINDOW = 206;
    int WITH = 207;
    int WORK = 208;
    int WRITE = 209;
    int YEAR = 210;
    int ABS = 211;
    int ABSVAL = 212;
    int ACTION = 213;
    int ALWAYS = 214;
    int BLOB = 215;
    int C = 216;
    int CALLED = 217;
    int CLOB = 218;
    int COBOL = 219;
    int COMMITTED = 220;
    int CONCAT = 221;
    int CONTAINS = 222;
    int CYCLE = 223;
    int DATA = 224;
    int DATE = 225;
    int DAY = 226;
    int DEFINER = 227;
    int DETERMINISTIC = 228;
    int DYNAMIC = 229;
    int ENFORCED = 230;
    int FORTRAN = 231;
    int GENERATED = 232;
    int IDENTITY_VAL_LOCAL = 233;
    int INCREMENT = 234;
    int INITIAL = 235;
    int INOUT = 236;
    int INTERVAL = 237;
    int INVOKER = 238;
    int LANGUAGE = 239;
    int LARGE = 240;
    int LENGTH = 241;
    int LEVEL = 242;
    int LIMIT = 243;
    int LOCKS = 244;
    int LOCKSIZE = 245;
    int LOGGED = 246;
    int MATCHED = 247;
    int MAXVALUE = 248;
    int MERGE = 249;
    int MINVALUE = 250;
    int MOD = 251;
    int MODIFIES = 252;
    int MODIFY = 253;
    int MONTH = 254;
    int _MORE = 255;
    int MUMPS = 256;
    int NAME = 257;
    int NCLOB = 258;
    int NULLABLE = 259;
    int NULLS = 260;
    int NUMBER = 261;
    int OBJECT = 262;
    int OFFSET = 263;
    int PASCAL = 264;
    int PLI = 265;
    int PRECISION = 266;
    int RELEASE = 267;
    int REPEATABLE = 268;
    int RESTART = 269;
    int RETURNS = 270;
    int ROLLUP = 271;
    int ROW = 272;
    int SAVEPOINT = 273;
    int SCALE = 274;
    int SECURITY = 275;
    int SERIALIZABLE = 276;
    int SQL_TSI_FRAC_SECOND = 277;
    int SQL_TSI_SECOND = 278;
    int SQL_TSI_MINUTE = 279;
    int SQL_TSI_HOUR = 280;
    int SQL_TSI_DAY = 281;
    int SQL_TSI_WEEK = 282;
    int SQL_TSI_MONTH = 283;
    int SQL_TSI_QUARTER = 284;
    int SQL_TSI_YEAR = 285;
    int START = 286;
    int STATEMENT = 287;
    int SYNONYM = 288;
    int THEN = 289;
    int TIME = 290;
    int TIMESTAMP = 291;
    int TIMESTAMPADD = 292;
    int TIMESTAMPDIFF = 293;
    int TRUNCATE = 294;
    int TYPE = 295;
    int UNCOMMITTED = 296;
    int USAGE = 297;
    int WHEN = 298;
    int DERBYPLAN = 299;
    int BOOLEAN = 300;
    int CALL = 301;
    int CURDATE = 302;
    int CURRENT_ROLE = 303;
    int CURTIME = 304;
    int DATABASE = 305;
    int GET_CURRENT_CONNECTION = 306;
    int EXPLAIN = 307;
    int BIGINT = 308;
    int LONG = 309;
    int LTRIM = 310;
    int NONE = 311;
    int OVER = 312;
    int ROLE = 313;
    int ROWNUMBER = 314;
    int RTRIM = 315;
    int SUBSTR = 316;
    int XML = 317;
    int XMLEXISTS = 318;
    int XMLPARSE = 319;
    int XMLQUERY = 320;
    int XMLSERIALIZE = 321;
    int AFTER = 322;
    int AGGREGATE = 323;
    int BEFORE = 324;
    int CLASS = 325;
    int COMPRESS = 326;
    int CONTENT = 327;
    int CS = 328;
    int CURSORS = 329;
    int DB2SQL = 330;
    int DERBY = 331;
    int DERBY_JDBC_RESULT_SET = 332;
    int DEFRAGMENT = 333;
    int DIRTY = 334;
    int DOCUMENT = 335;
    int EACH = 336;
    int EMPTY = 337;
    int EXCLUSIVE = 338;
    int FN = 339;
    int INDEX = 340;
    int INPLACE = 341;
    int JAVA = 342;
    int LCASE = 343;
    int LOCATE = 344;
    int LOCK = 345;
    int MESSAGE_LOCALE = 346;
    int METHOD = 347;
    int MODE = 348;
    int NEW = 349;
    int NEW_TABLE = 350;
    int NVARCHAR = 351;
    int OJ = 352;
    int OFF = 353;
    int OLD = 354;
    int OLD_TABLE = 355;
    int OUT = 356;
    int PARAMETER = 357;
    int PASSING = 358;
    int PROPERTIES = 359;
    int PURGE = 360;
    int READS = 361;
    int REF = 362;
    int REFERENCING = 363;
    int RENAME = 364;
    int RESET = 365;
    int RESULT = 366;
    int RETAIN = 367;
    int RETURNING = 368;
    int RR = 369;
    int RS = 370;
    int STATISTICS = 371;
    int SEQUENCE = 372;
    int SEQUENTIAL = 373;
    int SETS = 374;
    int SHARE = 375;
    int SQLID = 376;
    int SPECIFIC = 377;
    int SQRT = 378;
    int STABILITY = 379;
    int STRIP = 380;
    int STYLE = 381;
    int TRIGGER = 382;
    int TRUNCATE_END = 383;
    int UCASE = 384;
    int UR = 385;
    int WHITESPACE = 386;
    int DOUBLE_QUOTE = 387;
    int PERCENT = 388;
    int AMPERSAND = 389;
    int QUOTE = 390;
    int LEFT_BRACE = 391;
    int RIGHT_BRACE = 392;
    int LEFT_PAREN = 393;
    int RIGHT_PAREN = 394;
    int ASTERISK = 395;
    int HASH = 396;
    int PLUS_SIGN = 397;
    int COMMA = 398;
    int MINUS_SIGN = 399;
    int PERIOD = 400;
    int SOLIDUS = 401;
    int COLON = 402;
    int DOUBLE_COLON = 403;
    int SEMICOLON = 404;
    int LESS_THAN_OPERATOR = 405;
    int LESS_THAN_OR_EQUALS_OPERATOR = 406;
    int EQUALS_OPERATOR = 407;
    int NOT_EQUALS_OPERATOR = 408;
    int NOT_EQUALS_OPERATOR2 = 409;
    int GREATER_THAN_OPERATOR = 410;
    int GREATER_THAN_OR_EQUALS_OPERATOR = 411;
    int QUESTION_MARK = 412;
    int UNDERSCORE = 413;
    int VERTICAL_BAR = 414;
    int LEFT_BRACKET = 415;
    int RIGHT_BRACKET = 416;
    int CONCATENATION_OPERATOR = 417;
    int FIELD_REFERENCE = 418;
    int ELLIPSIS = 419;
    int IDENTIFIER = 420;
    int K = 421;
    int M = 422;
    int G = 423;
    int LETTER = 424;
    int DIGIT = 425;
    int DELIMITED_IDENTIFIER = 426;
    int EXACT_NUMERIC = 427;
    int UINT = 428;
    int LENGTH_MODIFIER = 429;
    int STRING = 430;
    int HEX_STRING = 431;
    int APPROXIMATE_NUMERIC = 432;
    int INTERVAL_LITERAL = 433;
    int INTERVAL_STRING = 434;
    int INTERVAL_QUALIFIER = 435;
    int SINGLE_DATETIME_FIELD = 436;
    int START_FIELD = 437;
    int END_FIELD = 438;
    int NON_SECOND_DATETIME_FIELD = 439;
    int YEAR_MONTH_LITERAL = 440;
    int DAY_TIME_LITERAL = 441;
    int DAY_TIME_INTERVAL = 442;
    int SECONDS_VALUE = 443;
    int TIME_INTERVAL = 444;

    int DEFAULT = 0;

    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "\"add\"",
            "\"all\"",
            "\"allocate\"",
            "\"alter\"",
            "\"and\"",
            "\"any\"",
            "\"are\"",
            "\"as\"",
            "\"asc\"",
            "\"assertion\"",
            "\"at\"",
            "\"authorization\"",
            "\"avg\"",
            "\"begin\"",
            "\"between\"",
            "\"binary\"",
            "\"bit\"",
            "\"both\"",
            "\"by\"",
            "\"cascade\"",
            "\"cascaded\"",
            "\"case\"",
            "\"cast\"",
            "\"char\"",
            "\"character\"",
            "\"character_length\"",
            "\"check\"",
            "\"close\"",
            "\"coalesce\"",
            "\"collate\"",
            "\"collation\"",
            "\"column\"",
            "\"commit\"",
            "\"connect\"",
            "\"connection\"",
            "\"constraint\"",
            "\"constraints\"",
            "\"continue\"",
            "\"convert\"",
            "\"corresponding\"",
            "\"count\"",
            "\"create\"",
            "\"cross\"",
            "\"current\"",
            "\"current_date\"",
            "\"current_time\"",
            "\"current_timestamp\"",
            "\"current_user\"",
            "\"cursor\"",
            "\"d\"",
            "\"deallocate\"",
            "\"dec\"",
            "\"decimal\"",
            "\"declare\"",
            "\"default\"",
            "\"deferrable\"",
            "\"deferred\"",
            "\"delete\"",
            "\"desc\"",
            "\"describe\"",
            "\"diagnostics\"",
            "\"disconnect\"",
            "\"distinct\"",
            "\"double\"",
            "\"drop\"",
            "\"else\"",
            "\"end\"",
            "\"end-exec\"",
            "\"escape\"",
            "\"except\"",
            "\"exception\"",
            "\"exec\"",
            "\"execute\"",
            "\"exists\"",
            "\"external\"",
            "\"false\"",
            "\"fetch\"",
            "\"first\"",
            "\"float\"",
            "\"for\"",
            "\"foreign\"",
            "\"found\"",
            "\"from\"",
            "\"full\"",
            "\"function\"",
            "\"get\"",
            "\"global\"",
            "\"go\"",
            "\"goto\"",
            "\"grant\"",
            "\"group\"",
            "\"having\"",
            "\"hour\"",
            "\"identity\"",
            "\"immediate\"",
            "\"in\"",
            "\"indicator\"",
            "\"initially\"",
            "\"inner\"",
            "\"input\"",
            "\"insensitive\"",
            "\"insert\"",
            "\"int\"",
            "\"integer\"",
            "\"intersect\"",
            "\"into\"",
            "\"is\"",
            "\"isolation\"",
            "\"join\"",
            "\"key\"",
            "\"last\"",
            "\"leading\"",
            "\"left\"",
            "\"like\"",
            "\"lower\"",
            "\"match\"",
            "\"max\"",
            "\"min\"",
            "\"minute\"",
            "\"module\"",
            "\"national\"",
            "\"natural\"",
            "\"nchar\"",
            "\"next\"",
            "\"no\"",
            "\"not\"",
            "\"null\"",
            "\"nullif\"",
            "\"numeric\"",
            "\"of\"",
            "\"on\"",
            "\"only\"",
            "\"open\"",
            "\"option\"",
            "\"or\"",
            "\"order\"",
            "\"outer\"",
            "\"output\"",
            "\"overlaps\"",
            "\"pad\"",
            "\"partial\"",
            "\"prepare\"",
            "\"preserve\"",
            "\"primary\"",
            "\"prior\"",
            "\"privileges\"",
            "\"procedure\"",
            "\"public\"",
            "\"read\"",
            "\"real\"",
            "\"references\"",
            "\"relative\"",
            "\"restrict\"",
            "\"revoke\"",
            "\"right\"",
            "\"rollback\"",
            "\"rows\"",
            "\"schema\"",
            "\"scroll\"",
            "\"second\"",
            "\"select\"",
            "\"session_user\"",
            "\"set\"",
            "\"smallint\"",
            "\"some\"",
            "\"space\"",
            "\"sql\"",
            "\"sqlcode\"",
            "\"sqlerror\"",
            "\"sqlstate\"",
            "\"substring\"",
            "\"sum\"",
            "\"system_user\"",
            "\"t\"",
            "\"table\"",
            "\"temporary\"",
            "\"timezone_hour\"",
            "\"timezone_minute\"",
            "\"to\"",
            "\"transaction\"",
            "\"translate\"",
            "\"translation\"",
            "\"trailing\"",
            "\"trim\"",
            "\"true\"",
            "\"ts\"",
            "\"union\"",
            "\"unique\"",
            "\"unknown\"",
            "\"update\"",
            "\"upper\"",
            "\"user\"",
            "\"using\"",
            "\"value\"",
            "\"values\"",
            "\"varbinary\"",
            "\"varchar\"",
            "\"varying\"",
            "\"view\"",
            "\"whenever\"",
            "\"where\"",
            "\"window\"",
            "\"with\"",
            "\"work\"",
            "\"write\"",
            "\"year\"",
            "\"abs\"",
            "\"absval\"",
            "\"action\"",
            "\"always\"",
            "\"blob\"",
            "\"c\"",
            "\"called\"",
            "\"clob\"",
            "\"cobol\"",
            "\"committed\"",
            "\"concat\"",
            "\"contains\"",
            "\"cycle\"",
            "\"data\"",
            "\"date\"",
            "\"day\"",
            "\"definer\"",
            "\"deterministic\"",
            "\"dynamic\"",
            "\"enforced\"",
            "\"fortran\"",
            "\"generated\"",
            "\"identity_val_local\"",
            "\"increment\"",
            "\"initial\"",
            "\"inout\"",
            "\"interval\"",
            "\"invoker\"",
            "\"language\"",
            "\"large\"",
            "\"length\"",
            "\"level\"",
            "\"limit\"",
            "\"locks\"",
            "\"locksize\"",
            "\"logged\"",
            "\"matched\"",
            "\"maxvalue\"",
            "\"merge\"",
            "\"minvalue\"",
            "\"mod\"",
            "\"modifies\"",
            "\"modify\"",
            "\"month\"",
            "\"more\"",
            "\"mumps\"",
            "\"name\"",
            "\"nclob\"",
            "\"nullable\"",
            "\"nulls\"",
            "\"number\"",
            "\"object\"",
            "\"offset\"",
            "\"pascal\"",
            "\"pli\"",
            "\"precision\"",
            "\"release\"",
            "\"repeatable\"",
            "\"restart\"",
            "\"returns\"",
            "\"rollup\"",
            "\"row\"",
            "\"savepoint\"",
            "\"scale\"",
            "\"security\"",
            "\"serializable\"",
            "\"sql_tsi_frac_second\"",
            "\"sql_tsi_second\"",
            "\"sql_tsi_minute\"",
            "\"sql_tsi_hour\"",
            "\"sql_tsi_day\"",
            "\"sql_tsi_week\"",
            "\"sql_tsi_month\"",
            "\"sql_tsi_quarter\"",
            "\"sql_tsi_year\"",
            "\"start\"",
            "\"statement\"",
            "\"synonym\"",
            "\"then\"",
            "\"time\"",
            "\"timestamp\"",
            "\"timestampadd\"",
            "\"timestampdiff\"",
            "\"truncate\"",
            "\"type\"",
            "\"uncommitted\"",
            "\"usage\"",
            "\"when\"",
            "\"--sqlkvplan\"",
            "\"boolean\"",
            "\"call\"",
            "\"curdate\"",
            "\"current_role\"",
            "\"curtime\"",
            "\"database\"",
            "\"getCurrentConnection\"",
            "\"explain\"",
            "\"bigint\"",
            "\"long\"",
            "\"ltrim\"",
            "\"none\"",
            "\"over\"",
            "\"role\"",
            "\"row_number\"",
            "\"rtrim\"",
            "\"substr\"",
            "\"xml\"",
            "\"xmlexists\"",
            "\"xmlparse\"",
            "\"xmlquery\"",
            "\"xmlserialize\"",
            "\"after\"",
            "\"aggregate\"",
            "\"before\"",
            "\"class\"",
            "\"compress\"",
            "\"content\"",
            "\"cs\"",
            "\"cursors\"",
            "\"db2sql\"",
            "\"sqlkv\"",
            "\"sqlkv_jdbc_result_set\"",
            "\"defragment\"",
            "\"dirty\"",
            "\"document\"",
            "\"each\"",
            "\"empty\"",
            "\"exclusive\"",
            "\"fn\"",
            "\"index\"",
            "\"inplace\"",
            "\"java\"",
            "\"lcase\"",
            "\"locate\"",
            "\"lock\"",
            "\"message_locale\"",
            "\"method\"",
            "\"mode\"",
            "\"new\"",
            "\"new_table\"",
            "\"nvarchar\"",
            "\"oj\"",
            "\"off\"",
            "\"old\"",
            "\"old_table\"",
            "\"out\"",
            "\"parameter\"",
            "\"passing\"",
            "\"properties\"",
            "\"purge\"",
            "\"reads\"",
            "\"ref\"",
            "\"referencing\"",
            "\"rename\"",
            "\"reset\"",
            "\"result\"",
            "\"retain\"",
            "\"returning\"",
            "\"rr\"",
            "\"rs\"",
            "\"statistics\"",
            "\"sequence\"",
            "\"sequential\"",
            "\"sets\"",
            "\"share\"",
            "\"sqlid\"",
            "\"specific\"",
            "\"sqrt\"",
            "\"stability\"",
            "\"strip\"",
            "\"style\"",
            "\"trigger\"",
            "\"truncate_end\"",
            "\"ucase\"",
            "\"ur\"",
            "\"whitespace\"",
            "\"\\\"\"",
            "\"%\"",
            "\"&\"",
            "\"\\\'\"",
            "\"{\"",
            "\"}\"",
            "\"(\"",
            "\")\"",
            "\"*\"",
            "\"#\"",
            "\"+\"",
            "\",\"",
            "\"-\"",
            "\".\"",
            "\"/\"",
            "\":\"",
            "\"::\"",
            "\";\"",
            "\"<\"",
            "\"<=\"",
            "\"=\"",
            "\"<>\"",
            "\"!=\"",
            "\">\"",
            "\">=\"",
            "\"?\"",
            "\"_\"",
            "\"|\"",
            "\"[\"",
            "\"]\"",
            "\"||\"",
            "\"->\"",
            "\"...\"",
            "<IDENTIFIER>",
            "\"K\"",
            "\"M\"",
            "\"G\"",
            "<LETTER>",
            "<DIGIT>",
            "<DELIMITED_IDENTIFIER>",
            "<EXACT_NUMERIC>",
            "<UINT>",
            "<LENGTH_MODIFIER>",
            "<STRING>",
            "<HEX_STRING>",
            "<APPROXIMATE_NUMERIC>",
            "<INTERVAL_LITERAL>",
            "<INTERVAL_STRING>",
            "<INTERVAL_QUALIFIER>",
            "<SINGLE_DATETIME_FIELD>",
            "<START_FIELD>",
            "<END_FIELD>",
            "<NON_SECOND_DATETIME_FIELD>",
            "<YEAR_MONTH_LITERAL>",
            "<DAY_TIME_LITERAL>",
            "<DAY_TIME_INTERVAL>",
            "<SECONDS_VALUE>",
            "<TIME_INTERVAL>",
    };

}
